### ISSUE TITLE
Feature Request: Mouse speed settings

### ISSUE THREAD

**Issue by developomp** [the-via/app#116]
Add a new tab to sidebar for changing cursor movement mode and related values such as max movement speed.

QMK docs: https://docs.qmk.fm/#/feature_mouse_keys

**Comment by wilba** [comment]
All the settings for mouse keys are compiled into the firmware. Changing them to be runtime configurable would require changing a lot of the QMK core code. If you are interested in changing the settings for mouse keys, you can build VIA compatible firmware with different mouse key settings, it will work in VIA as usual.
