### ISSUE TITLE
[Feature - Request] Knob support

### ISSUE THREAD

**Issue by xIUPITERx** [the-via/app#136]
Support knobs by displaying one circle instead of three different buttons.
When you select the circle (knob), you should then be able to set the following options.
- Click
- Rotate clockwise
- turn counter clockwise

**Comment by wilba** [comment]
This is already done, however, not all the definitions have been updated to use this feature.
If you want this for an existing keyboard that works in VIA, contact the keyboard manufacturer/designer.
