### ISSUE TITLE
macros, symbols, and modifier keys no longer loading from config

### ISSUE THREAD

**Issue by olee-n4l** [the-via/app#147]
browser version is no longer loading in macros (M0-M7 are present in json but aren't recorded when config is loaded in). Most modifier keys and most symbol keys are also not loaded

**Comment by liv-lee** [comment]
_olee-n4l_ is my work account 🤦‍♀️

Manually bound keys that weren't loaded and comparing the json I see they're all ones that have been renamed. It's a shame there isn't an auto migration from old to new names as my board became pretty unusable due immediately after loading in the old config, not a biggie, but perhaps worth putting a clear a note in the release notes

**Comment by olivia** [comment]
Hi 👋 thank you for the bug report, macros not loading correctly that are using old keycode names may have been fixed today but I'm paging @wilba to confirm
