### ISSUE TITLE
Please add a Privacy Policy

### ISSUE THREAD

**Issue by yadomi** [the-via/app#244]
The app, whether used in Electron from [the release repo](https://github.com/the-via/releases) or on <https://usevia.app>, collects data without informing the user. As a user, I am concerned about the collection and use of my personal data. I believe that other users may share this concern, especially given the nature of the app, which deals with keyboard input. (See https://github.com/the-via/app/issues/226.)

The application does not provide clear and transparent information about the data collection practices, including the use of any third-party tools or services such as Sentry and Application Insights. 

Please add a Privacy Policy (eg: in settings tab?) that clearly explains the data collection practices, including the types of data being collected, the purposes for which the data is being used, and any third-party tools or services that are involved in the data collection process. The Privacy Policy should also outline the user's rights regarding their data, such as the right to access, correct, or delete their data.

Idealy, an opt-out option could be added to the application that allows users to easily opt-out of data collection. This could be implemented as a toggle switch in the application's settings menu. 

Yadomi

---

For references:

- https://gdpr-info.eu/art-12-gdpr/
- https://gdpr-info.eu/art-13-gdpr/

**Sentry**:
https://github.com/the-via/app/blob/d76f990104124c97e290e584a56622f5134b3c8f/src/index.tsx#L17-L23
https://github.com/the-via/app/blob/d76f990104124c97e290e584a56622f5134b3c8f/src/store/index.ts#L28
https://github.com/the-via/app/blob/d76f990104124c97e290e584a56622f5134b3c8f/src/Routes.tsx#L39
https://github.com/the-via/app/blob/d76f990104124c97e290e584a56622f5134b3c8f/src/store/errorsListener.ts#L14

**ApplicationInsights**
https://github.com/the-via/app/blob/d76f990104124c97e290e584a56622f5134b3c8f/src/index.tsx#L25-L32
https://github.com/the-via/app/blob/d76f990104124c97e290e584a56622f5134b3c8f/api/host.json#L4-L9

**Comment by Cipulot** [comment]
Addressed with https://github.com/the-via/app/pull/273
