### ISSUE TITLE
Unable to configure Nuphy Air75 V2

### ISSUE THREAD

**Issue by batizza** [the-via/app#246]
I am not able to configure my new Nuphy Air75 V2 keyboard in VIA.

I have followed all the instructions from https://nuphy.com/pages/via-usage-guide-for-nuphy-keyboards step by step both through VIA website and Windows app but it does not work. I have enabled Design tab in settings, loaded the correct JSON file from Nuphy website and connected my keyboard in the pop-up window.

Keyboard is visible in Key Tester tab but still not visible in Configure tab. I have tried to authorize it again using the button from Configure tab where the pop-up window showed my keyboard but it did not help.

**Comment by MatthewMenze** [comment]
I am having the same issue in Chrome on Mac (M3 Max, Sonoma 14.4.1 if it matters). Followed the instructions at the link indicated, enabled design settings, and it shows up correctly as paired in the pop up window. Also works correctly in the keyboard tester. No issues loading the JSON either.

Same keyboard as well.

**Comment by gabrieldaj** [comment]
Same keyboard here, I have a windows 11 machine and tryied to connect throw chrome and edge, in both cases the configure tab did not work

**Comment by batizza** [comment]
I actually figured it out. Probably your json file is not compatible with QMK firmware flashed on your keyboard. JSON file offered on Nuphy website is compatible with the latest 2.0.3 firmware. So you either use QMK tool to flash 2.0.3 firmware or find JSON file that is compatible with the previous firmware version.
For me flashing 2.0.3 firmware resolved the issue.

**Comment by rras3k** [comment]
Update the QMK firmware (with Qmk tools software) by pressing the little button under the keycap 'CAPS' before to connect the usb cable.
