### ISSUE TITLE
LT(1,KC_CAPS) is converted into LT(1,KC_SPC)

### ISSUE THREAD

**Issue by b22790188** [the-via/app#249]
When I try to turn capslock into LT(1,KC_CAPS) using ANY key with rainy75, I get space signal on tap  instead.

**Comment by mmwuzhi** [comment]
@b22790188 
How was the issue completed? I encountered the same problem and couldn't find a solution.

**Comment by b22790188** [comment]
I forgot where I found the article that mentioned rainy 75 does not support this key, so the issue was ultimately not resolved, and it wasn't a problem with VIA 😞
