### ISSUE TITLE
VIA Not Authorizing NuPhy Air75 v2. If switched to old v2 version, error "Object should NOT have additional properties"

### ISSUE THREAD

**Issue by sp3ckn** [the-via/app#253]
![image](https://github.com/the-via/app/assets/170993588/398bd486-1c42-4f34-9803-08fd9523dd81)
![image](https://github.com/the-via/app/assets/170993588/26306e2c-0d86-4055-b65b-861cfb96a187)
![image](https://github.com/the-via/app/assets/170993588/b0513bb3-59ee-47b0-9b02-7a684f1f216b)

New NuPhy air75 v2 not workling in VIA app.

Help?

**Comment by domman95** [comment]
Same issue here - any help from you guys?

**Comment by HannyNguyen** [comment]
you need update firmware for Nuphy at first and then run VIA....

**Comment by tedivm** [comment]
I ran into this problem as well, and the firmware upgrade resolved it.

Instructions for upgrading firmware: https://nuphy.com/pages/qmk-firmwares
