### ISSUE TITLE
Add Encoder Map support

### ISSUE THREAD

**Issue by drashna** [the-via/app#26]
The Encoder Map feature supports dynamic keymaps already.  

This means that all that needs to be done is support added to the firmware, and app support. 

https://docs.qmk.fm/#/feature_encoders?id=encoder-map

https://github.com/qmk/qmk_firmware/blob/master/quantum/dynamic_keymap.c#L122-L143

**Comment by olivia** [comment]
Closed by the combination of #35 & @wilba's qmk PR
