### ISSUE TITLE
[bug] Not displaying Nuphy Air75 V2

### ISSUE THREAD

**Issue by megaroeny** [the-via/app#263]
I uploaded the JSON to the configurator for a Nuphy Air75 V2 keyboard. The data shows that the JSON is correct for this keyboard. But the issue is when I go to accept the prompt to connect to the keyboard/device, nothing appears on the Configure tab.

Here is a screen recording of the issue:

https://github.com/user-attachments/assets/6204a954-1318-4ec0-9c5d-3b8bbaf98d72

Thank you for your help!

**Comment by megaroeny** [comment]
I also tried this on Windows in Edge + Chrome and still the same result.

The screen recording above was done on macOS in Arc (chromium).

**Comment by megaroeny** [comment]
Upon flashing the latest firmware for this keyboard, the Configuration tab finally showed my keyboard. I wonder if this is an issue during manufacturing and if newer firmware needs to be installed before finalizing manufacturing.

**Comment by louia** [comment]
@megaroeny I have the same issue as you on brave on macos, latest firmware : 2.1.0 flashed with QMK. Have you the prooblem already ?

**Comment by megaroeny** [comment]
> @megaroeny I have the same issue as you on brave on macos, latest firmware : 2.1.0 flashed with QMK. Have you the prooblem already ?

Last time I tried on Windows I couldn't get it to connect in Arc. I had to use Edge. Maybe a software issue I'm guessing. Maybe reopen the issue or another related one if you're having issues also.

**Comment by louia** [comment]
@megaroeny I contacted Nuphy and they send me the updated json file for my Air96 v2. I linked the version they send me bellow :
[nuphy-air96-v2-via3(1).json](https://github.com/user-attachments/files/18276980/nuphy-air96-v2-via3.1.json)

**Comment by megaroeny** [comment]
> I contacted Nuphy and they send me the updated json file for my Air96 v2. I linked the version they send me bellow : [nuphy-air96-v2-via3(1).json](https://github.com/user-attachments/files/18276980/nuphy-air96-v2-via3.1.json)

I probably shouldn't use that, different model keyboard. If it happens again I'll reach out to them. It worked before, not sure why it's not now.

**Comment by yiancar** [comment]
Please reach out to the creators of your keyboard.
We do not have the device to be able to debug.
