### ISSUE TITLE
garbled problem

### ISSUE THREAD

**Issue by aihk** [the-via/app#48]
When the labels attribute in the .json file has Chinese characters, there will be garbled characters. Can you fix this problem?

**Comment by olivia** [comment]
Would you mind providing a sample `.json` file to replicate with?

**Comment by olivia** [comment]
Closing due to bug not being reproducible.

**Comment by aihk** [comment]
> Would you mind providing a sample `.json` file to replicate with?
Sorry ~ I saw the news today. How can I provide you .json
