### ISSUE TITLE
Is the package install version of VIA client no longer updated?

### ISSUE THREAD

**Issue by yoichiro** [the-via/app#53]
I have a question about the install package of VIA client app. We already can use VIA web app on our Web browser, and I know that the code set has been continuously improving within a month and we can use the latest version of the VIA web app anytime. That is, can we recognize that the version 2.0.5 of the install package is the last version? Also, can we think that the new version of the install package no longer releases?

**Comment by olivia** [comment]
Hi Yoichiro, thank you for your question. Version 2.0.5 points to the via web app through an electron shell. So if you use the app or the web site, either will be kept up-to-date.

**Comment by yoichiro** [comment]
@olivia Hi, Olivia, thank you for your answer! OK, I was able to understand that both web app and electron app are keeping as latest.
