### ISSUE TITLE
VIA support for QMK Tap dance

### ISSUE THREAD

**Issue by Moghul** [the-via/app#68]
Hi, I couldn't figure out what the right repo for this issue is, so hopefully this is ok.

Any chance tap dance is coming in the future? I'd love to be able to have different behavior for tapping and holding several of my buttons.

Alternatively, is there already a way to do this, and maybe I missed it?

**Comment by pontus-albert** [comment]
I don't exactly know what features are included under the 'tap dance' headline, but having one behavior when you hold a button and another when you tap it is doable in Via. 

Check out [the list of key codes](https://github.com/qmk/qmk_firmware/blob/master/docs/keycodes.md).  If you want to use for instance shift and caps lock, I think the code is `MT(MOD_LSFT, KC_CAPS)` (wrote that from memory so check for yourself). If you want to change layer and do some other thing I think it's `LT(1, KC_CAPS)` for example.

**Comment by Moghul** [comment]
Thank you! I didn't realize the features were supported under a different name!

**Comment by vinorodrigues** [comment]
Tap Dance is different from Mod Tap, or Layer Tap.  While VIA supports both Mod Tap and Layer Tap, it does not support Tap Dance.

**Comment by StevenCurran** [comment]
This does not appear to work for say remapping a hold of x to cntrl + x. 

I have tried with via by using: MT(MOD_LCTL | KC_X, KC_X) but VIA rejects it.

Any suggestions on how it could be achieved?

**Comment by AdrienLF** [comment]
Here is the doc about tap dance, which is different from Mod Tap or Layer Tap. It would be really useful to have it in VIA, as it is one of the most unique (and useful) feature of QMK.

https://github.com/samhocevar-forks/qmk-firmware/blob/master/docs/feature_tap_dance.md

**Comment by peterjc** [comment]
Upstream version of the QMK tap-dance docs is https://docs.qmk.fm/features/tap_dance from source https://github.com/qmk/qmk_firmware/blob/master/docs/features/tap_dance.md
