### ISSUE TITLE
Mapping changes do not save to keyboard

### ISSUE THREAD

**Issue by eliotstock** [the-via/app#72]
Using the usevia.app webapp version, I can remap keys on my Keychron v1. The changes I make will have immediate effect if I switch to another application on the same computer and test them.

However, if I then unplug the keyboard and plug it into another computer, the changes are lost and the remapped key return to their original function.

**Comment by vinorodrigues** [comment]
That's not a VIA issue.  The fact that you can use it right after changing implies that the keymap dynamic memory is indeed stored.  If you're having reset issue on inserting into another PC then it's something you're going in that sequence that is resetting the EEPROM *(that in the Keychron V1 is actually emulated space from the f/w flash region)*.  Reset can only occur on certain conditions *(there are quite a few, so my may inadvertently be doing one of them)*.  Try asking on the Keychron discord server for help specific to the Keychron boards.

**Comment by eliotstock** [comment]
Thanks, makes sense. Will do.
