### ISSUE TITLE
Missing definitions in V3

### ISSUE THREAD

**Issue by kuhaniz** [the-via/app#74]
Hello, I did some edits to hineybush/ibis firmware and it seems to be calling v3 definitions so it is giving a 404 error to missing definitions. You can see the screenshots below. I also noticed the default firmware is v2. Not sure is it my settings or not but is there a way to change the required definitions value or to have the definitions available in v3 ?

https://imgur.com/a/Tb3QZ9h

**Comment by wilba** [comment]
I'll look into this ASAP

**Comment by wilba** [comment]
the v3 definition for ibis has been added now, so VIA should work with new firmware built from QMK master
