### ISSUE TITLE
Azure 404 is breaking VIA

### ISSUE THREAD

**Issue by anthonydiiorio** [the-via/app#79]
I'm having trouble using VIA because of a 404 error when I load my base keymap json file. 

When I upload the file for my Keychron V1, `v1_ansi_knob_rev1.05.json` into the design tab, the keyboard will not detect and I notice a 404 error in the console that leads to an Azure Static Web Apps 404 page.

This problem persists on desktop (v2.05) and the web app.

I tried installing desktop version 1.3.1 and it works fine as expected.

![msedge_326pk1i8Urw1](https://user-images.githubusercontent.com/1933848/206840316-61620111-2226-4819-974e-e375a9bac317.png)

![msedge_33sr6LcXKHu0](https://user-images.githubusercontent.com/1933848/206840322-f064c6d5-f473-45e2-8483-a3d741fff67f.png)

**Comment by wilba** [comment]
What happens if you uncheck "Use V3 definitions" before loading the JSON?

**Comment by anthonydiiorio** [comment]
Interesting that solves my issue. JSON loads fine and the editor becomes available.
