### ISSUE TITLE
"Authorize device" button does nothing, 404 on JSON request

### ISSUE THREAD

**Issue by eliotstock** [the-via/app#81]
This is a regression - the app used to work with my keyboard, which is a Keychron v1.

From Chrome dev tools, the request is for https://usevia.app/definitions/v2/875823889.json. This is a 404.

**Comment by aliev** [comment]
the same issue with keychron k6 pro

**Comment by PCC17** [comment]
I am having the same problem!
The 404 error makes the AppImage and web version unusable!

**Comment by wilba** [comment]
See #91
