### ISSUE TITLE
F keys in macros are not working

### ISSUE THREAD

**Issue by mrtnRitter** [the-via/app#82]
When a macro contains a f key, the macro is not send. Tested on Keychron Q6 Ansi Encoder and Iso Encoder.

Steps to reproduce:
Fork QMK, compile using qmk compile -kb keychron/q6/iso_encoder -km keychron, open VIA, add macro {KC_LALT,KC_F4}, assign macro to a key, press the key and nothing happens.

Further investigation:
- keyboard was put into debug mode and QMK console prints all raw keypressed - when the macro was pressed, no keypress was registered (not 0x00, literally nothing as the key wasn't pressed)
- the issues persists for all keymaps

**Comment by wilba** [comment]
Thanks for the bug report, we added delays to the macro spec and a bug was introduced when keycodes had digits in them.
