### ISSUE TITLE
Question: Is it possible to map two keys to a single key?

### ISSUE THREAD

**Issue by davidhaley** [the-via/app#98]
Macros support mapping a single key to multiple keys. I am wondering if the opposite is possible (mapping two keys to one key).

For example, I would like to:

1. Map CapsLock to Escape (done)
2. Map CapsLock+Space to Backspace **(I am not sure if this is possible)**

Thank you.

**Comment by calebmeyer** [comment]
I thought about doing it with Mod Tap and a layer shift, but Mod Tap only takes modifier keys. This might require going direct to qmk

**Comment by AndSDev** [comment]
You can do this with layer and LT-key. For example (with layer 2):
Main layer: map CapsLock to `LT(2,KC_ESC)` with `Any` key (in special keymap) - its means "switch to layer 2 while held, esc on tap".
Layer 2: map Space to Backspace.

**Comment by davidhaley** [comment]
> 

Thanks @AndSDev.

I don't seem to have (or see) `LT`:

![image](https://user-images.githubusercontent.com/11729897/226195312-837869c3-f78e-4445-935c-b68fbb7c77be.png)
![image](https://user-images.githubusercontent.com/11729897/226195337-bb15f522-b9e9-4cd8-b3f3-21b097d3f0b5.png)

**Comment by davidhaley** [comment]
> You can do this with layer and LT-key. For example (with layer 2): Main layer: map CapsLock to `LT(2,KC_ESC)` with `Any` key (in special keymap) - its means "switch to layer 2 while held, esc on tap". Layer 2: map Space to Backspace.

That worked, thank you @AndSDev!

FYI for others that read this, I had to use `LT(3, KC_ESC)` instead, as my 'second' layer is actually Layer 4 (since I'm using the Windows layout).
