### ISSUE TITLE
Can't assign layer shift to keys

### ISSUE THREAD

**Issue by Muchieman7** [the-via/app#99]
I'm not sure when this started happening, but it's happening with both of my devices now (kbd75v2 and kbdpad mkii)
Short video here which is basically self explanitory:
https://www.youtube.com/shorts/xSAwyBvtQEI

I'm not sure if this is helpful, but in the "Command for <ID>" log in the console, when I try to apply any MO(n) to a key I get:
0: 5
1: 2
2: 5
3: 2
4: 0
...

the remainingvalues being 0. It looks like it's targeting the key with the first 4 values, then the rest is meant to be the layer shift but it's just blank? Is this a known issue?

edit: I have reset cookies/permissions and tried again, same result :/

**Comment by Muchieman7** [comment]
After testing locally, I get some maybe more helpful errors
![image](https://user-images.githubusercontent.com/49734536/211645880-fe7479db-6125-4190-814b-0320c52269c7.png)

**Comment by gemcosta** [comment]
I'm also getting this issue on a QK65. I can assign any other type of key, but when attempting to assign MO(1) (or any other momentary layer function), the key is assigned "blank" and is not usable. 

So at least this confirms I am not the only one experiencing this issue and is most likely a bug with VIA and not an issue with the keyboard or firmware.

**Comment by gemcosta** [comment]
After some digging, I was able to find a workaround.

When configuring the key you want to be a MO(n) key, instead of using the options under the "LAYERS" category, go to the "SPECIAL" category and select "ANY". For me, it was the very last key in this category.

Then, you are able to create your own using QMK keycode. Then I simply entered `MO(1)` and hit CONFIRM. Voila! I was able to assign MO(1) to the key that was originally having trouble.

**Comment by taandsoul** [comment]
Same issue here, my 60% keyboard it's partially useless now ⚠️

**Comment by Muchieman7** [comment]
> Same issue here, my 60% keyboard it's partially useless now ⚠️
> 
> ![image](https://user-images.githubusercontent.com/44118603/211708412-dc4cfe62-fdea-4a6f-a632-60c78e33a3af.png)

make sure to check gemcosta's solution before giving up! I ended up just going back to plain QMK because I needed it to work, I'll come back to VIA at some point.

**Comment by wilba** [comment]
The recent change to advanced keycodes (i.e. the "Any" key) broke this, fixed now.

Thanks for reporting it so quickly!
